# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: ${paths.log_dir}/${task_name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}

job_logging:
  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${hydra.runtime.output_dir}/${task_name}.log

#hydra_logging:
#  version: 1
#  disable_existing_loggers: false
#  formatters:
#    simple:
#      format: '%(message)s'
#  handlers:
#    console:
#      class: logging.StreamHandler
#      formatter: simple
#      level: WARNING  # Suppress error logs
#  root:
#    level: WARNING


#job:
#    env_set:
#      COLUMNS: 120  # Set desired console width