_target_: src.models.clipseg.lightning_modules.CLIPSegLitModule
#  out: 1
#  depth: 3

mix: true
mix_text_max: 0.5
mix_text_min: 0.0

loss_fn:
  _target_: src.utils.clipseg_utils.loss.BinaryCrossEntropyWithLogitsLoss

optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 0.001

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 20000
  eta_min: 0.0001

model:
  _target_: src.models.clipseg.clipseg.CLIPDensePredT
  version: 'ViT-B/16'
  reduce_dim: 64
  complex_trans_conv: true
  extract_layers: [3, 7, 9]
  fix_shift: False

