_target_: src.models.UNetLitModule

model:
  _target_: src.models.baseline.unet.unet.SEVIRUNet
  in_channels: 3
  out_channels: 3
  start_filters: 32

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 2e-4
  weight_decay: 0.0
  betas: [0.9, 0.999]
  eps: 1e-8

criterion:
  _target_: src.utils.clipseg_utils.loss.BinaryCrossEntropyWithLogitsLoss

scheduler: null
compile: false