defaults:
  - model_checkpoint
#  - early_stopping
  - model_summary
#  - rich_progress_bar
  - slack_alert
#  - annotation_logger
  - debris_wandb_logger
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/dice"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False
  every_n_epochs: 20

#early_stopping:
#  monitor: "val/dice"
#  patience: 50
#  mode: "max"

model_summary:
  max_depth: 2
  summarize_kwargs:
    save_dir: ${paths.output_dir}  # assuming save_dir is stored under the wandb key in your config
