# @package _global_

defaults:
  - data: debris_predict # debris_one_hot, debris_predict
  - model: clip_seg
  - callbacks: debris_prediction_logger # debris_prediction_logger # default, debris_prediction_logger
  - logger: null # null, wandb
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default
  - _self_
  - experiment: null
  - optional local: default

task_name: "eval"
test: false
predict: true
seed: 42

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: null <-- REPLACE WITH YOUR CHECKPOINT PATH

name: null # name of the experiment, used for output directory
paths:
  output_dir: ${local.prediction_output_dir}/${name}
  log_dir: ${paths.output_dir}